/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: e8bb8a7b0d47189cd9b950e8dab86309)
interface __BaseEnv_Env {
	CONTENT_BUCKET: R2Bucket;
	VECTOR_DB: VectorizeIndex;
	LOADER: WorkerLoader;
	AI: Ai;
	ASSETS: Fetcher;
	AdvisorAgent: DurableObjectNamespace<import("./src/server").AdvisorAgent>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "AdvisorAgent";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
