/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 35b9f1a133391c640b5662a51d3b2218)
interface __BaseEnv_Env {
	CONTENT_BUCKET: R2Bucket;
	VECTOR_DB: VectorizeIndex;
	AI: Ai;
	ASSETS: Fetcher;
	AdvisorAgent: DurableObjectNamespace<import("./src/server").AdvisorAgent>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "AdvisorAgent";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
